#Create a new namespace "rak"
---
apiVersion: v1
kind: Namespace
metadata:
  name: rak


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rak-app
  namespace: rak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rakapp
  template:
    metadata:
      labels:
        app: rakapp
    spec:
      containers:
      - name: rakapp
        image:  sharon111edapal/samplerak:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: rak
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rakapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Assuming your application is running on port 8080
      nodePort: 30000   # You can specify a specific nodePort or omit it to let Kubernetes assign one
    
